### ISSUE TITLE
400 Bad Request with valid extractedValue

### ISSUE THREAD

**Issue by clarkritchie** [upbound/provider-datadog#25]
Hello!  I am creating synthetic tests based off of known-good manifests of existing synthetic tests.

My workflow is to import an existing test using `managementPolicies: ["Observe"]`, and then essentially copy the YAML to a new manifest and apply it.  This workflow has worked great for monitors, but with synthetic tests I am running into this error:

```json
                "message": "apply failed: error creating synthetics API test from https://api.datadoghq.com/api/v1/synthetics/tests/api: 400 Bad Request: {\"errors\":[\"'extractedValues' value '{'field': 'location', 'name': 'LOCATION_FROM_CALL_1', 'parser': {'type': 'raw', 'value': ''}, 'secure': False, 'type': 'http_header'}' is invalid\"]}: ",
```

In this case, the corresponding YAML is:

```yaml
        extractedValue:
          - field: location
            name: LOCATION_FROM_CALL_1
            parser:
              - type: raw
            secure: false
            type: http_header
```

...which is valid, and I can't figure out why this is would be returning a 400.

**Comment by clarkritchie** [comment]
@khalilj-appsflyer Thanks for your contribution here.  I have a number of multi-step API tests that I would like to bring under Crossplane management, however I cannot seem to get past the error above, wherein Datadog returns a 400 for my schema which appears to be valid.  Do you have any suggestions on how I can debug this further?  Basic api tests [like this](https://github.com/upbound/provider-datadog/blob/main/examples-generated/synthetics/v1alpha1/test.yaml) work fine.  Thanks for any suggestions.

**Comment by khalilj-appsflyer** [comment]
Hi @clarkritchie , I can think of starting the provider locally, apply your test and debug.

**Comment by clarkritchie** [comment]
Thank you @khalilj-appsflyer!  Do you need any more info to make a test case?  This happens to be the first `apiStep` in one of our more complex synthetics.

```
- allowFailure: false
        assertion:
          - operator: lessThan
            target: "3000"
            type: responseTime
          - operator: is
            target: "302"
            type: statusCode
          - operator: is
            property: location
            target: https://xxx
            type: header
        extractedValue:
          - field: location
            name: LOCATION_FROM_CALL_1
            parser:
              - type: raw
            secure: false
            type: http_header
          - field: set-cookie
            name: ORIGINAL_AUTH_URL
            parser:
              - type: regex
                value: original_auth_url[^;]*
            secure: false
            type: http_header
          - field: set-cookie
            name: CLIENT_INFO
            parser:
              - type: regex
                value: client_info[^;]*
            secure: false
            type: http_header
        isCritical: true
        name: Initial call to get login
        requestDefinition:
          - allowInsecure: false
            dnsServerPort: 0
            followRedirects: false
            method: GET
            noSavingResponseBody: false
            numberOfPackets: 0
            persistCookies: false
            port: 0
            shouldTrackHops: false
            timeout: 10
            url: https://xxx
        retry:
          - count: 5
            interval: 500
        subtype: http
```

**Comment by clarkritchie** [comment]
I am able to compile and run this locally now, however I am not sure how to debug much further.

Would this be a multi-step equivalent of [the example](https://github.com/upbound/provider-datadog/blob/main/examples-generated/synthetics/v1alpha1/test.yaml)?

```
apiVersion: synthetics.datadog.upbound.io/v1alpha1
kind: Test
metadata:
  name: test-uptime-v2
spec:
  forProvider:
    apiStep:
      - name: Step 1 - Check Homepage
        requestDefinition:
          - method: GET
            url: https://www.example.org
        assertion:
          - operator: is
            target: "200"
            type: statusCode
        requestHeaders:
          Content-Type: application/json
      - name: Step 2 - Check API Endpoint
        requestDefinition:
          - method: GET
            url: https://api.example.org/endpoint
        assertion:
          - operator: is
            target: "200"
            type: statusCode
        requestHeaders:
          Content-Type: application/json
    locations:
      - aws:eu-central-1
    message: OMG
    name: v2 Uptime test on example.org
    optionsList:
      - monitorOptions:
          - renotifyInterval: 120
        retry:
          - count: 2
            interval: 300
        tickEvery: 900
    status: live
    subtype: http
    tags:
      - foo:bar
      - env:test
    type: api
```

I am seeing:

```console
    message: 'apply failed: error creating synthetics API test from https://api.datadoghq.com/api/v1/synthetics/tests/api:
      400 Bad Request: {"errors":["Required parameter ''method'' is missing\nRequired
      parameter ''url'' is missing\nMinimum number of elements in parameter ''assertions''
      should be 1"]}: '
```
